import Head from 'next/head'
import Image from 'next/image'
import VotingCard from '../components/VotingCard'
import styles from '../styles/Home.module.css'
import useSWR from "swr";

const fetcher = (url) => fetch(url).then((res) => res.json());
export default function Home() {
  const { data, error } = useSWR(
    "http://127.0.0.1:5000/",
    fetcher
  );

  if (error) return "An error has occurred.";
  if (!data) return "Loading..."; 
  

  let start = data.start;
  // let [teams, setTeams] = useState([]);
  let question = data.scenarios[start].question;
  // let question = "Who Should Dom sit next to on the bus?"
  let options = [];
  console.log('start: ', start, 'data_scen_start: ', data.scenarios[start].options);
  data.scenarios[start].options.map((el) => {
    options.push({
      text : el,
      link : "/api/"+data.scenarios[start].meta[el]
    }) 
  });
  // let answers = [{text: "Friend 1", link: "/api/1"}, {text: "Friend 2", link: "/api/2"} ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Link in my bio: Questions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VotingCard
        question={question}
        options={options}
      />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
