import Head from 'next/head'
import Image from 'next/image'
import VotingCard from '../components/VotingCard'
import styles from '../styles/Home.module.css'

export default function Home() {

  // let [teams, setTeams] = useState([]);
  let question = "Who Should Dom sit next to on the bus?"
  let answers = [{text: "Friend 1", link: "/api/1"}, {text: "Friend 2", link: "/api/2"} ]
  let sample_props = {question: question, answers: answers}
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Link in my bio: Questions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VotingCard
        question={question}
        answers={answers}
      />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
